name: Build and Deploy Image Container

on:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch: # Enable manual triggering of the workflow

env:
  DOTNET_VERSION: '8.0.x' 
  BUILD_CONFIGURATION: 'Release'    
  PUBLISH_PROJECT: 'AssetsDemo.Frontend.WebApp/AssetsDemo.Frontend.WebApp.csproj'
  DOCKER_HUB_REPOSITORY: 'assets-demo-frontend'

defaults:
  run:
    working-directory: ./src

# Ensures only one execution per branch will run at a time.
concurrency:
  group: ${{ github.ref }}
  
jobs:
  ci-build:

    runs-on: ubuntu-latest
    outputs:
      nuget_version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Setup GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: ${{ secrets.PACKAGES_FEED_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

    - name: Cache .NET Core packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} -p:GeneratePackageOnBuild=false
      
    - name: Publish Web App
      run: dotnet publish ${{ env.PUBLISH_PROJECT }} --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output './../publish'
   
    - name: Login to Docker Hub Registry
      uses: docker/login-action@v3
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}      

    - name: Build and Push Image to Docker Hub Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.WebApp
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.DOCKER_HUB_REPOSITORY}}:${{ steps.gitversion.outputs.nuGetVersionV2 }}
        labels: |
            org.opencontainers.image.title=Assets Demo Api
            org.opencontainers.image.description=Assets Demo Api
            org.opencontainers.image.version=${{ steps.set_gitversion.outputs.nuget_version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.gitversion.outputs.nuGetVersionV2 }}
        release_name: Release ${{ steps.gitversion.outputs.nuGetVersionV2 }}

  deploy-to-qa:
    needs: [ci-build]
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to QA Azure Container App
        run: |
          echo Deploying version ${{ needs.build.outputs.nuget_version }}
          az containerapp update --name ${{ secrets.AZURE_CONTAINERAPP_NAME_QA }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_QA }} --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ needs.ci-build.outputs.nuget_version }}

